// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageOperator int32

const (
	MessageOperator_UPDATE MessageOperator = 0
	MessageOperator_DELETE MessageOperator = 1
)

var MessageOperator_name = map[int32]string{
	0: "UPDATE",
	1: "DELETE",
}

var MessageOperator_value = map[string]int32{
	"UPDATE": 0,
	"DELETE": 1,
}

func (x MessageOperator) String() string {
	return proto.EnumName(MessageOperator_name, int32(x))
}

func (MessageOperator) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

type SystemMessageType int32

const (
	SystemMessageType_NODE_STORAGE_INFO       SystemMessageType = 0
	SystemMessageType_NODE_STORAGE_INFO_REPLY SystemMessageType = 1
	SystemMessageType_DATA_MIGRATE            SystemMessageType = 1001
	SystemMessageType_DATA_MIGRATE_REPLY      SystemMessageType = 1002
	SystemMessageType_DATA_PUSH               SystemMessageType = 2001
	SystemMessageType_DATA_PUSH_REPLY         SystemMessageType = 2002
	SystemMessageType_DATA_PULL               SystemMessageType = 2003
	SystemMessageType_DATA_PULL_REPLY         SystemMessageType = 2004
)

var SystemMessageType_name = map[int32]string{
	0:    "NODE_STORAGE_INFO",
	1:    "NODE_STORAGE_INFO_REPLY",
	1001: "DATA_MIGRATE",
	1002: "DATA_MIGRATE_REPLY",
	2001: "DATA_PUSH",
	2002: "DATA_PUSH_REPLY",
	2003: "DATA_PULL",
	2004: "DATA_PULL_REPLY",
}

var SystemMessageType_value = map[string]int32{
	"NODE_STORAGE_INFO":       0,
	"NODE_STORAGE_INFO_REPLY": 1,
	"DATA_MIGRATE":            1001,
	"DATA_MIGRATE_REPLY":      1002,
	"DATA_PUSH":               2001,
	"DATA_PUSH_REPLY":         2002,
	"DATA_PULL":               2003,
	"DATA_PULL_REPLY":         2004,
}

func (x SystemMessageType) String() string {
	return proto.EnumName(SystemMessageType_name, int32(x))
}

func (SystemMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

type SystemMessage struct {
	Type                 SystemMessageType `protobuf:"varint,1,opt,name=type,proto3,enum=model.SystemMessageType" json:"type,omitempty"`
	Sender               int32             `protobuf:"varint,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Content              []byte            `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SystemMessage) Reset()         { *m = SystemMessage{} }
func (m *SystemMessage) String() string { return proto.CompactTextString(m) }
func (*SystemMessage) ProtoMessage()    {}
func (*SystemMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *SystemMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemMessage.Unmarshal(m, b)
}
func (m *SystemMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemMessage.Marshal(b, m, deterministic)
}
func (m *SystemMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemMessage.Merge(m, src)
}
func (m *SystemMessage) XXX_Size() int {
	return xxx_messageInfo_SystemMessage.Size(m)
}
func (m *SystemMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SystemMessage proto.InternalMessageInfo

func (m *SystemMessage) GetType() SystemMessageType {
	if m != nil {
		return m.Type
	}
	return SystemMessageType_NODE_STORAGE_INFO
}

func (m *SystemMessage) GetSender() int32 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func (m *SystemMessage) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type EventMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventMessage) Reset()         { *m = EventMessage{} }
func (m *EventMessage) String() string { return proto.CompactTextString(m) }
func (*EventMessage) ProtoMessage()    {}
func (*EventMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *EventMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventMessage.Unmarshal(m, b)
}
func (m *EventMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventMessage.Marshal(b, m, deterministic)
}
func (m *EventMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventMessage.Merge(m, src)
}
func (m *EventMessage) XXX_Size() int {
	return xxx_messageInfo_EventMessage.Size(m)
}
func (m *EventMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EventMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EventMessage proto.InternalMessageInfo

type TopicMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicMessage) Reset()         { *m = TopicMessage{} }
func (m *TopicMessage) String() string { return proto.CompactTextString(m) }
func (*TopicMessage) ProtoMessage()    {}
func (*TopicMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *TopicMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicMessage.Unmarshal(m, b)
}
func (m *TopicMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicMessage.Marshal(b, m, deterministic)
}
func (m *TopicMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicMessage.Merge(m, src)
}
func (m *TopicMessage) XXX_Size() int {
	return xxx_messageInfo_TopicMessage.Size(m)
}
func (m *TopicMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TopicMessage proto.InternalMessageInfo

type DataMessage struct {
	Operator             MessageOperator `protobuf:"varint,1,opt,name=operator,proto3,enum=model.MessageOperator" json:"operator,omitempty"`
	Namespace            string          `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Table                string          `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	Id                   string          `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Version              int32           `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Content              []byte          `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DataMessage) Reset()         { *m = DataMessage{} }
func (m *DataMessage) String() string { return proto.CompactTextString(m) }
func (*DataMessage) ProtoMessage()    {}
func (*DataMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *DataMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataMessage.Unmarshal(m, b)
}
func (m *DataMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataMessage.Marshal(b, m, deterministic)
}
func (m *DataMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataMessage.Merge(m, src)
}
func (m *DataMessage) XXX_Size() int {
	return xxx_messageInfo_DataMessage.Size(m)
}
func (m *DataMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DataMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DataMessage proto.InternalMessageInfo

func (m *DataMessage) GetOperator() MessageOperator {
	if m != nil {
		return m.Operator
	}
	return MessageOperator_UPDATE
}

func (m *DataMessage) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DataMessage) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *DataMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DataMessage) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *DataMessage) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterEnum("model.MessageOperator", MessageOperator_name, MessageOperator_value)
	proto.RegisterEnum("model.SystemMessageType", SystemMessageType_name, SystemMessageType_value)
	proto.RegisterType((*SystemMessage)(nil), "model.SystemMessage")
	proto.RegisterType((*EventMessage)(nil), "model.EventMessage")
	proto.RegisterType((*TopicMessage)(nil), "model.TopicMessage")
	proto.RegisterType((*DataMessage)(nil), "model.DataMessage")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xcf, 0xae, 0x9a, 0x40,
	0x14, 0xc6, 0xef, 0xd8, 0x0b, 0x96, 0x53, 0x2f, 0xe0, 0xe4, 0x56, 0x49, 0xda, 0x85, 0x71, 0x65,
	0x4d, 0xe3, 0xc2, 0x3e, 0x01, 0x09, 0x53, 0x6b, 0x82, 0x62, 0x46, 0x5c, 0x74, 0x45, 0x50, 0x26,
	0x0d, 0x89, 0x30, 0x04, 0x26, 0x26, 0x3e, 0x5a, 0x57, 0x7d, 0x86, 0xfe, 0x79, 0x89, 0xf6, 0x29,
	0x1a, 0xc6, 0xc1, 0x62, 0xdd, 0xf1, 0x3b, 0xe7, 0x17, 0xe6, 0xfb, 0x26, 0x03, 0x4f, 0x19, 0xab,
	0xaa, 0xf8, 0x0b, 0x9b, 0x15, 0x25, 0x17, 0x1c, 0x6b, 0x19, 0x4f, 0xd8, 0x71, 0xcc, 0xe1, 0x69,
	0x7b, 0xae, 0x04, 0xcb, 0x56, 0x97, 0x2d, 0x7e, 0x0f, 0x8f, 0xe2, 0x5c, 0x30, 0x07, 0x8d, 0xd0,
	0xc4, 0x9c, 0x3b, 0x33, 0xa9, 0xcd, 0x6e, 0x9c, 0xf0, 0x5c, 0x30, 0x2a, 0x2d, 0x3c, 0x00, 0xbd,
	0x62, 0x79, 0xc2, 0x4a, 0xa7, 0x33, 0x42, 0x13, 0x8d, 0x2a, 0xc2, 0x0e, 0x74, 0x0f, 0x3c, 0x17,
	0x2c, 0x17, 0xce, 0x8b, 0x11, 0x9a, 0xf4, 0x68, 0x83, 0x63, 0x13, 0x7a, 0xe4, 0xc4, 0x72, 0xa1,
	0xfe, 0x55, 0x73, 0xc8, 0x8b, 0xf4, 0xd0, 0xf0, 0x57, 0x04, 0xaf, 0xbc, 0x58, 0xc4, 0x4d, 0x9e,
	0x39, 0xbc, 0xe4, 0x05, 0x2b, 0x63, 0xc1, 0x4b, 0x95, 0x69, 0xa0, 0x32, 0x29, 0x23, 0x50, 0x5b,
	0x7a, 0xf5, 0xf0, 0x5b, 0x30, 0xf2, 0x38, 0x63, 0x55, 0x11, 0x1f, 0x98, 0x0c, 0x66, 0xd0, 0x7f,
	0x03, 0xfc, 0x0c, 0x9a, 0x88, 0xf7, 0x47, 0x26, 0x93, 0x19, 0xf4, 0x02, 0xd8, 0x84, 0x4e, 0x9a,
	0x38, 0x8f, 0x72, 0xd4, 0x49, 0x93, 0xba, 0xc1, 0x89, 0x95, 0x55, 0xca, 0x73, 0x47, 0x93, 0xd5,
	0x1a, 0x6c, 0x77, 0xd3, 0x6f, 0xba, 0x4d, 0xdf, 0x81, 0xf5, 0x5f, 0x28, 0x0c, 0xa0, 0xef, 0x36,
	0x9e, 0x1b, 0x12, 0xfb, 0xa1, 0xfe, 0xf6, 0x88, 0x4f, 0x42, 0x62, 0xa3, 0xe9, 0x37, 0x04, 0xfd,
	0xbb, 0x4b, 0xc5, 0xaf, 0xa1, 0xbf, 0x0e, 0x3c, 0x12, 0x6d, 0xc3, 0x80, 0xba, 0x0b, 0x12, 0x2d,
	0xd7, 0x1f, 0x03, 0xfb, 0x01, 0xbf, 0x81, 0xe1, 0xdd, 0x38, 0xa2, 0x64, 0xe3, 0x7f, 0xb6, 0x11,
	0xee, 0x43, 0xcf, 0x73, 0x43, 0x37, 0x5a, 0x2d, 0x17, 0xb4, 0x3e, 0xe7, 0x77, 0x17, 0x0f, 0x01,
	0xb7, 0x47, 0x4a, 0xfd, 0xd3, 0xc5, 0x26, 0x18, 0x72, 0xb1, 0xd9, 0x6d, 0x3f, 0xd9, 0xdf, 0x2d,
	0xfc, 0x0c, 0xd6, 0x95, 0x95, 0xf5, 0xc3, 0x6a, 0x59, 0xbe, 0x6f, 0xff, 0x6c, 0x5b, 0xbe, 0xaf,
	0xac, 0x5f, 0xd6, 0x5e, 0x97, 0xef, 0xe8, 0xc3, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf2, 0xfc,
	0xcd, 0x9e, 0x58, 0x02, 0x00, 0x00,
}
