// Code generated by protoc-gen-go. DO NOT EDIT.
// source: packet.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PacketMode int32

const (
	PacketMode_TCP       PacketMode = 0
	PacketMode_UDP       PacketMode = 1
	PacketMode_HTTP      PacketMode = 2
	PacketMode_Multicast PacketMode = 3
	PacketMode_Broadcast PacketMode = 4
)

var PacketMode_name = map[int32]string{
	0: "TCP",
	1: "UDP",
	2: "HTTP",
	3: "Multicast",
	4: "Broadcast",
}

var PacketMode_value = map[string]int32{
	"TCP":       0,
	"UDP":       1,
	"HTTP":      2,
	"Multicast": 3,
	"Broadcast": 4,
}

func (x PacketMode) String() string {
	return proto.EnumName(PacketMode_name, int32(x))
}

func (PacketMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{0}
}

type PacketType int32

const (
	PacketType_System PacketType = 0
	PacketType_Event  PacketType = 1
	PacketType_Topic  PacketType = 2
	PacketType_Data   PacketType = 3
)

var PacketType_name = map[int32]string{
	0: "System",
	1: "Event",
	2: "Topic",
	3: "Data",
}

var PacketType_value = map[string]int32{
	"System": 0,
	"Event":  1,
	"Topic":  2,
	"Data":   3,
}

func (x PacketType) String() string {
	return proto.EnumName(PacketType_name, int32(x))
}

func (PacketType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{1}
}

type Packet struct {
	Version              int32      `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Id                   string     `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Mode                 PacketMode `protobuf:"varint,3,opt,name=mode,proto3,enum=model.PacketMode" json:"mode,omitempty"`
	Type                 PacketType `protobuf:"varint,4,opt,name=type,proto3,enum=model.PacketType" json:"type,omitempty"`
	From                 int32      `protobuf:"varint,5,opt,name=from,proto3" json:"from,omitempty"`
	To                   int32      `protobuf:"varint,6,opt,name=to,proto3" json:"to,omitempty"`
	Receivers            []int32    `protobuf:"varint,7,rep,packed,name=receivers,proto3" json:"receivers,omitempty"`
	Content              []byte     `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{0}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Packet) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Packet) GetMode() PacketMode {
	if m != nil {
		return m.Mode
	}
	return PacketMode_TCP
}

func (m *Packet) GetType() PacketType {
	if m != nil {
		return m.Type
	}
	return PacketType_System
}

func (m *Packet) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *Packet) GetTo() int32 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *Packet) GetReceivers() []int32 {
	if m != nil {
		return m.Receivers
	}
	return nil
}

func (m *Packet) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterEnum("model.PacketMode", PacketMode_name, PacketMode_value)
	proto.RegisterEnum("model.PacketType", PacketType_name, PacketType_value)
	proto.RegisterType((*Packet)(nil), "model.Packet")
}

func init() { proto.RegisterFile("packet.proto", fileDescriptor_e9ef1a6541f9f9e7) }

var fileDescriptor_e9ef1a6541f9f9e7 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x37, 0xe9, 0xbf, 0xed, 0xb0, 0x2e, 0x71, 0x4e, 0x39, 0x78, 0x28, 0x82, 0x50, 0xf6,
	0xd0, 0x83, 0x5e, 0x3c, 0xeb, 0x2a, 0x5e, 0x16, 0x4a, 0xac, 0x1f, 0xa0, 0xb6, 0x11, 0x82, 0xdb,
	0xa6, 0xb4, 0xe3, 0x42, 0xbf, 0xab, 0x1f, 0x46, 0x12, 0x29, 0x7b, 0xd9, 0xdb, 0x7b, 0x6f, 0x26,
	0x6f, 0x7e, 0x04, 0x36, 0x43, 0xdd, 0x7c, 0x6b, 0x2a, 0x86, 0xd1, 0x92, 0xc5, 0xa8, 0xb3, 0xad,
	0x3e, 0xde, 0xfe, 0x32, 0x88, 0x4b, 0x9f, 0xa3, 0x84, 0xe4, 0xa4, 0xc7, 0xc9, 0xd8, 0x5e, 0xb2,
	0x8c, 0xe5, 0x91, 0x5a, 0x2c, 0x6e, 0x81, 0x9b, 0x56, 0xf2, 0x8c, 0xe5, 0xa9, 0xe2, 0xa6, 0xc5,
	0x3b, 0x08, 0xdd, 0x6b, 0x19, 0x64, 0x2c, 0xdf, 0xde, 0x5f, 0x17, 0xbe, 0xaa, 0xf8, 0xaf, 0x39,
	0xd8, 0x56, 0x2b, 0x3f, 0x76, 0x6b, 0x34, 0x0f, 0x5a, 0x86, 0x17, 0xd6, 0xaa, 0x79, 0xd0, 0xca,
	0x8f, 0x11, 0x21, 0xfc, 0x1a, 0x6d, 0x27, 0x23, 0x7f, 0xd4, 0x6b, 0x77, 0x91, 0xac, 0x8c, 0x7d,
	0xc2, 0xc9, 0xe2, 0x0d, 0xa4, 0xa3, 0x6e, 0xb4, 0x71, 0x44, 0x32, 0xc9, 0x82, 0x3c, 0x52, 0xe7,
	0xc0, 0x91, 0x37, 0xb6, 0x27, 0xdd, 0x93, 0x5c, 0x67, 0x2c, 0xdf, 0xa8, 0xc5, 0xee, 0x5e, 0x01,
	0xce, 0x58, 0x98, 0x40, 0x50, 0x3d, 0x97, 0x62, 0xe5, 0xc4, 0xc7, 0xbe, 0x14, 0x0c, 0xd7, 0x10,
	0xbe, 0x55, 0x55, 0x29, 0x38, 0x5e, 0x41, 0x7a, 0xf8, 0x39, 0x92, 0x69, 0xea, 0x89, 0x44, 0xe0,
	0xec, 0xd3, 0x68, 0xeb, 0xd6, 0xdb, 0x70, 0xf7, 0xb8, 0xf4, 0x38, 0x6e, 0x04, 0x88, 0xdf, 0xe7,
	0x89, 0x74, 0x27, 0x56, 0x98, 0x42, 0xf4, 0x72, 0xd2, 0x3d, 0x09, 0xe6, 0x64, 0x65, 0x07, 0xd3,
	0x08, 0xee, 0x7a, 0xf7, 0x35, 0xd5, 0x22, 0xf8, 0x8c, 0xfd, 0x77, 0x3f, 0xfc, 0x05, 0x00, 0x00,
	0xff, 0xff, 0x70, 0xe1, 0x2b, 0x77, 0x7e, 0x01, 0x00, 0x00,
}
