// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeRole int32

const (
	NodeRole_NORMAL NodeRole = 0
	NodeRole_HOLDER NodeRole = 1
)

var NodeRole_name = map[int32]string{
	0: "NORMAL",
	1: "HOLDER",
}

var NodeRole_value = map[string]int32{
	"NORMAL": 0,
	"HOLDER": 1,
}

func (x NodeRole) String() string {
	return proto.EnumName(NodeRole_name, int32(x))
}

func (NodeRole) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}

type Node struct {
	Group                string   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Role                 NodeRole `protobuf:"varint,4,opt,name=role,proto3,enum=proto.NodeRole" json:"role,omitempty"`
	Ip                   string   `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	SocketPort           int32    `protobuf:"varint,6,opt,name=socketPort,proto3" json:"socketPort,omitempty"`
	HttpPort             int32    `protobuf:"varint,7,opt,name=httpPort,proto3" json:"httpPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *Node) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Node) GetRole() NodeRole {
	if m != nil {
		return m.Role
	}
	return NodeRole_NORMAL
}

func (m *Node) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Node) GetSocketPort() int32 {
	if m != nil {
		return m.SocketPort
	}
	return 0
}

func (m *Node) GetHttpPort() int32 {
	if m != nil {
		return m.HttpPort
	}
	return 0
}

func init() {
	proto.RegisterEnum("proto.NodeRole", NodeRole_name, NodeRole_value)
	proto.RegisterType((*Node)(nil), "proto.Node")
}

func init() { proto.RegisterFile("node.proto", fileDescriptor_0c843d59d2d938e7) }

var fileDescriptor_0c843d59d2d938e7 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xcb, 0x4f, 0x49,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x1b, 0x19, 0xb9, 0x58, 0xfc,
	0xf2, 0x53, 0x52, 0x85, 0x44, 0xb8, 0x58, 0xd3, 0x8b, 0xf2, 0x4b, 0x0b, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x38, 0x83, 0x20, 0x1c, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x26, 0x05, 0x46, 0x0d,
	0xd6, 0x20, 0xa6, 0xcc, 0x14, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x66, 0xb0,
	0x22, 0x30, 0x5b, 0x48, 0x99, 0x8b, 0xa5, 0x28, 0x3f, 0x27, 0x55, 0x82, 0x45, 0x81, 0x51, 0x83,
	0xcf, 0x88, 0x1f, 0x62, 0xbe, 0x1e, 0xc8, 0xd0, 0xa0, 0xfc, 0x9c, 0xd4, 0x20, 0xb0, 0x24, 0xd8,
	0xa0, 0x02, 0x09, 0x56, 0xb0, 0x36, 0xa6, 0xcc, 0x02, 0x21, 0x39, 0x2e, 0xae, 0xe2, 0xfc, 0xe4,
	0xec, 0xd4, 0x92, 0x80, 0xfc, 0xa2, 0x12, 0x09, 0x36, 0xb0, 0x05, 0x48, 0x22, 0x42, 0x52, 0x5c,
	0x1c, 0x19, 0x25, 0x25, 0x05, 0x60, 0x59, 0x76, 0xb0, 0x2c, 0x9c, 0xaf, 0xa5, 0xc4, 0xc5, 0x01,
	0x33, 0x5d, 0x88, 0x8b, 0x8b, 0xcd, 0xcf, 0x3f, 0xc8, 0xd7, 0xd1, 0x47, 0x80, 0x01, 0xc4, 0xf6,
	0xf0, 0xf7, 0x71, 0x71, 0x0d, 0x12, 0x60, 0x4c, 0x62, 0x03, 0xbb, 0xc2, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x10, 0xb2, 0x02, 0x0b, 0xf3, 0x00, 0x00, 0x00,
}
